#!/usr/bin/env bash
# This Script is to install Nginx & configure 301 redirect for /redirect_me

set -e  # Exit on error

# Update the package list and install Nginx
apt-get update -y
apt-get install -y nginx


# Start nginx service to ensure it's running
service nginx start

# Create a simple HTML file for the root endpoint
echo "Holberton School for the win!" > /var/www/html/index.html

# Use sed to insert a redirection block inside the server block
# This matches the "server {" line and appends the redirection
sed -i '/server_name _;/a location /redirect_me {\n    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default

# Start and reload Nginx using service (not systemctl)
service nginx start
service nginx reload
